name: custompaint
description: "A new Flutter project using CustomPaint."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"  # Safe range

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets must be under flutter: section
  assets:
    - assets/room.json

  # Uncomment and add assets if you use images
  # assets:
  #   - assets/images/

  # Uncomment if you plan to use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
